package m_Chapter;

public class A_Exception {
	public static void main(String[] args) {
		
		try {
			int division = 10/0;
		}catch(Exception e) {
			System.out.println("0으로 나눌 수 없습니다.");
		}
		
		try {
			String text = null;
			// null 계산은 예의 - NullPointerException  발생
			System.out.println(text.length());
			int division = 10/0; 
			//정수를 0으로 나눌수 없음
			
		}catch(NullPointerException e) {
				System.out.println("널 참조발생");	
		}catch(ArithmeticException e) {
			System.out.println("산술적 예외 발생");
		}
		
		
		// finally 블럭
		// : try-catch 구조의 일부( 선택사항)
		// : 예외 발생 여부와 관계없이 항상 실행되는 블록
		
		int [] numbers = new int [5];
		numbers[10]= 50;
		
		
	}
}
